### ISSUE TITLE
PHP8.1 Support

### ISSUE THREAD

**Issue by WebFX-dev** [chrisputnam9/pssh#40]
Running on PHP8.1 gives this deprecation notice:
`PHP Deprecated:  preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /usr/local/bin/pssh on line 1195`

**Comment by chrisputnam9** [comment]
Thanks! Fixed!

**Comment by WebFX-dev** [comment]
Your WebFX Support Request has been Received!

chrisputnam9/pssh,

Thank you for submitting your website request! This email is to confirm that your request has been received and added to our ticket queue. One of the WebFX Support team members will begin working on the ticket as soon as possible, and respond to you when complete.

You can check the status of or reply to the ticket at the following link: http://helpdesk.webpagefx.com/index.php?_m=tickets&_a=viewticket&ticketid=187088

    Using the following login:
    E-mail: ***@***.***
    Password: 21a2db05


***If your website is down, and it is currently outside of our business hours of 8AM-5PM EST Monday through Friday, please call 717-609-0360 and select option #2.***

Thank you!
- WebFX Support Team

**Comment by WebFX-dev** [comment]
Your WebFX Support Request has been Received!

chrisputnam9/pssh,

Thank you for submitting your website request! This email is to confirm that your request has been received and added to our ticket queue. One of the WebFX Support team members will begin working on the ticket as soon as possible, and respond to you when complete.

You can check the status of or reply to the ticket at the following link: http://helpdesk.webpagefx.com/index.php?_m=tickets&_a=viewticket&ticketid=187089

    Using the following login:
    E-mail: ***@***.***
    Password: 01990245


***If your website is down, and it is currently outside of our business hours of 8AM-5PM EST Monday through Friday, please call 717-609-0360 and select option #2.***

Thank you!
- WebFX Support Team
