### ISSUE TITLE
PHP8.2 Deprecation

### ISSUE THREAD

**Issue by theodoreslechta** [chrisputnam9/pssh#53]
PHP Deprecated:  Creation of dynamic property HJSONStringifier::$meta is deprecated in /usr/local/bin/pssh on line 1778

Occurs when running `pssh search {term}`

**Comment by chrisputnam9** [comment]
Fixed in branch feature-sprint-1.5 of [pcon](https://github.com/chrisputnam9/pcon) which should launch soon with feature-sprint-2.5 of pssh.

Also PR'd to PHP-HJSON https://github.com/hjson/hjson-php/pull/36
