### ISSUE TITLE
Empty string in alias_additional creates empty host in SSH config

### ISSUE THREAD

**Issue by theodoreslechta** [chrisputnam9/pssh#63]
In ssh_config_work.json: https://webpagefx.mangoapps.com/msc/MTQwNjYwOV8xMjE2MDUzMQ
The empty string results in an empty host entry in the generated SSH config. Deleting the empty string and regenerating the config resolves the issue

**Comment by chrisputnam9** [comment]
Using cleaning methods to address this:
 - If major issue found (empty key) during cleaning
 - Show warning & explanation
 - Mark config as exportable=false (for these and other key warnings)
 - Throw error when trying to export if exportable=false

**Comment by chrisputnam9** [comment]
Addressed in v2.5.2 - example output: https://cmp.onl/tnlx
